version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
    labels:
      - "actions"
      - "dependabot"
    reviewers:
      - "fr-platform/maintainers"
      
